spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:database/schema.sql
      data-locations: classpath:database/data.sql
      encoding: utf-8
logging:
  level:
    org:
      springframework: WARN
    com:
      example:
        todo:
          repository: DEBUG