spring:
  datasource:
    url: jdbc:mysql://localhost:3306/app
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:database/schema.sql
      data-locations: classpath:database/data.sql
      encoding: utf-8
  jpa:
    show-sql: true